/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ReadingEntry = IDL.Record({
  'minutes' : IDL.Nat,
  'category' : IDL.Text,
  'pages' : IDL.Nat,
});
export const MeditationSession = IDL.Record({
  'id' : IDL.Text,
  'durationSeconds' : IDL.Nat,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const WorkoutEntry = IDL.Record({
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'category' : IDL.Text,
});
export const DaySummary = IDL.Record({
  'reading' : IDL.Vec(ReadingEntry),
  'meditation' : IDL.Vec(MeditationSession),
  'tasks' : IDL.Vec(Task),
  'date' : IDL.Text,
  'mood' : IDL.Opt(IDL.Nat),
  'workout' : IDL.Vec(WorkoutEntry),
  'hydration' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMeditationSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'decrementHydration' : IDL.Func([IDL.Text], [], []),
  'getDailySummary' : IDL.Func([IDL.Text], [DaySummary], ['query']),
  'getHydrationByDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getMeditationByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MeditationSession)],
      ['query'],
    ),
  'getMoodByDate' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getReadingByDate' : IDL.Func([IDL.Text], [IDL.Vec(ReadingEntry)], ['query']),
  'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'getWorkoutsByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkoutEntry)],
      ['query'],
    ),
  'incrementHydration' : IDL.Func([IDL.Text], [], []),
  'removeMeditationSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeReadingEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeWorkoutEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setHydration' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setMood' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'toggleTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'upsertReadingEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'upsertWorkoutEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ReadingEntry = IDL.Record({
    'minutes' : IDL.Nat,
    'category' : IDL.Text,
    'pages' : IDL.Nat,
  });
  const MeditationSession = IDL.Record({
    'id' : IDL.Text,
    'durationSeconds' : IDL.Nat,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const WorkoutEntry = IDL.Record({
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'category' : IDL.Text,
  });
  const DaySummary = IDL.Record({
    'reading' : IDL.Vec(ReadingEntry),
    'meditation' : IDL.Vec(MeditationSession),
    'tasks' : IDL.Vec(Task),
    'date' : IDL.Text,
    'mood' : IDL.Opt(IDL.Nat),
    'workout' : IDL.Vec(WorkoutEntry),
    'hydration' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMeditationSession' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'decrementHydration' : IDL.Func([IDL.Text], [], []),
    'getDailySummary' : IDL.Func([IDL.Text], [DaySummary], ['query']),
    'getHydrationByDate' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getMeditationByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MeditationSession)],
        ['query'],
      ),
    'getMoodByDate' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getReadingByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReadingEntry)],
        ['query'],
      ),
    'getTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'getWorkoutsByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkoutEntry)],
        ['query'],
      ),
    'incrementHydration' : IDL.Func([IDL.Text], [], []),
    'removeMeditationSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeReadingEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeWorkoutEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setHydration' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setMood' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'toggleTask' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'upsertReadingEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'upsertWorkoutEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };