/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DaySummary {
  'reading' : Array<ReadingEntry>,
  'meditation' : Array<MeditationSession>,
  'tasks' : Array<Task>,
  'date' : string,
  'mood' : [] | [bigint],
  'workout' : Array<WorkoutEntry>,
  'hydration' : number,
}
export interface MeditationSession { 'id' : string, 'durationSeconds' : bigint }
export interface ReadingEntry {
  'minutes' : bigint,
  'category' : string,
  'pages' : bigint,
}
export interface Task { 'id' : string, 'text' : string, 'completed' : boolean }
export interface WorkoutEntry {
  'reps' : bigint,
  'sets' : bigint,
  'category' : string,
}
export interface _SERVICE {
  'addLitres' : ActorMethod<[string, number], undefined>,
  'addMeditationSession' : ActorMethod<[string, bigint], undefined>,
  'addTask' : ActorMethod<[string, string], undefined>,
  'getDailySummary' : ActorMethod<[string], DaySummary>,
  'getHydrationByDate' : ActorMethod<[string], number>,
  'getHydrationTarget' : ActorMethod<[string], number>,
  'getMeditationByDate' : ActorMethod<[string], Array<MeditationSession>>,
  'getMoodByDate' : ActorMethod<[string], [] | [bigint]>,
  'getReadingByDate' : ActorMethod<[string], Array<ReadingEntry>>,
  'getTasksByDate' : ActorMethod<[string], Array<Task>>,
  'getWorkoutsByDate' : ActorMethod<[string], Array<WorkoutEntry>>,
  'removeLitres' : ActorMethod<[string, number], undefined>,
  'removeMeditationSession' : ActorMethod<[string, string], undefined>,
  'removeReadingEntry' : ActorMethod<[string, string], undefined>,
  'removeTask' : ActorMethod<[string, string], undefined>,
  'removeWorkoutEntry' : ActorMethod<[string, string], undefined>,
  'setHydration' : ActorMethod<[string, number], undefined>,
  'setHydrationTarget' : ActorMethod<[string, number], undefined>,
  'setMood' : ActorMethod<[string, bigint], undefined>,
  'toggleTask' : ActorMethod<[string, string], undefined>,
  'upsertReadingEntry' : ActorMethod<
    [string, string, bigint, bigint],
    undefined
  >,
  'upsertWorkoutEntry' : ActorMethod<
    [string, string, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];