/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: string;
    text: string;
    completed: boolean;
}
export interface ReadingEntry {
    minutes: bigint;
    category: string;
    pages: bigint;
}
export interface DaySummary {
    reading: Array<ReadingEntry>;
    meditation: Array<MeditationSession>;
    tasks: Array<Task>;
    date: string;
    mood?: bigint;
    workout: Array<WorkoutEntry>;
    hydration: number;
}
export interface WorkoutEntry {
    reps: bigint;
    sets: bigint;
    category: string;
}
export interface MeditationSession {
    id: string;
    durationSeconds: bigint;
}
export interface backendInterface {
    addLitres(date: string, amount: number): Promise<void>;
    addMeditationSession(date: string, durationSeconds: bigint): Promise<void>;
    addTask(date: string, text: string): Promise<void>;
    getDailySummary(date: string): Promise<DaySummary>;
    getHydrationByDate(date: string): Promise<number>;
    getHydrationTarget(date: string): Promise<number>;
    getMeditationByDate(date: string): Promise<Array<MeditationSession>>;
    getMoodByDate(date: string): Promise<bigint | null>;
    getReadingByDate(date: string): Promise<Array<ReadingEntry>>;
    getTasksByDate(date: string): Promise<Array<Task>>;
    getWorkoutsByDate(date: string): Promise<Array<WorkoutEntry>>;
    removeLitres(date: string, amount: number): Promise<void>;
    removeMeditationSession(date: string, sessionId: string): Promise<void>;
    removeReadingEntry(date: string, category: string): Promise<void>;
    removeTask(date: string, taskId: string): Promise<void>;
    removeWorkoutEntry(date: string, category: string): Promise<void>;
    setHydration(date: string, amount: number): Promise<void>;
    setHydrationTarget(date: string, target: number): Promise<void>;
    setMood(date: string, score: bigint): Promise<void>;
    toggleTask(date: string, taskId: string): Promise<void>;
    upsertReadingEntry(date: string, category: string, pages: bigint, minutes: bigint): Promise<void>;
    upsertWorkoutEntry(date: string, category: string, reps: bigint, sets: bigint): Promise<void>;
}
import type { DaySummary as _DaySummary, MeditationSession as _MeditationSession, ReadingEntry as _ReadingEntry, Task as _Task, WorkoutEntry as _WorkoutEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLitres(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLitres(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLitres(arg0, arg1);
            return result;
        }
    }
    async addMeditationSession(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMeditationSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMeditationSession(arg0, arg1);
            return result;
        }
    }
    async addTask(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, arg1);
            return result;
        }
    }
    async getDailySummary(arg0: string): Promise<DaySummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySummary(arg0);
                return from_candid_DaySummary_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySummary(arg0);
            return from_candid_DaySummary_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHydrationByDate(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getHydrationByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHydrationByDate(arg0);
            return result;
        }
    }
    async getHydrationTarget(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getHydrationTarget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHydrationTarget(arg0);
            return result;
        }
    }
    async getMeditationByDate(arg0: string): Promise<Array<MeditationSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeditationByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeditationByDate(arg0);
            return result;
        }
    }
    async getMoodByDate(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodByDate(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodByDate(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReadingByDate(arg0: string): Promise<Array<ReadingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadingByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadingByDate(arg0);
            return result;
        }
    }
    async getTasksByDate(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksByDate(arg0);
            return result;
        }
    }
    async getWorkoutsByDate(arg0: string): Promise<Array<WorkoutEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutsByDate(arg0);
            return result;
        }
    }
    async removeLitres(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeLitres(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeLitres(arg0, arg1);
            return result;
        }
    }
    async removeMeditationSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMeditationSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMeditationSession(arg0, arg1);
            return result;
        }
    }
    async removeReadingEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReadingEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReadingEntry(arg0, arg1);
            return result;
        }
    }
    async removeTask(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTask(arg0, arg1);
            return result;
        }
    }
    async removeWorkoutEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkoutEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkoutEntry(arg0, arg1);
            return result;
        }
    }
    async setHydration(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHydration(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHydration(arg0, arg1);
            return result;
        }
    }
    async setHydrationTarget(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setHydrationTarget(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHydrationTarget(arg0, arg1);
            return result;
        }
    }
    async setMood(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMood(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMood(arg0, arg1);
            return result;
        }
    }
    async toggleTask(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTask(arg0, arg1);
            return result;
        }
    }
    async upsertReadingEntry(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertReadingEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertReadingEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async upsertWorkoutEntry(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertWorkoutEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertWorkoutEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_DaySummary_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaySummary): DaySummary {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reading: Array<_ReadingEntry>;
    meditation: Array<_MeditationSession>;
    tasks: Array<_Task>;
    date: string;
    mood: [] | [bigint];
    workout: Array<_WorkoutEntry>;
    hydration: number;
}): {
    reading: Array<ReadingEntry>;
    meditation: Array<MeditationSession>;
    tasks: Array<Task>;
    date: string;
    mood?: bigint;
    workout: Array<WorkoutEntry>;
    hydration: number;
} {
    return {
        reading: value.reading,
        meditation: value.meditation,
        tasks: value.tasks,
        date: value.date,
        mood: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.mood)),
        workout: value.workout,
        hydration: value.hydration
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
